"base_path": /home/rick/Lab/Dev/temp
"preserve_hierarchy": true

files:
  -
    source: 'Logic/*.resx'
    translation: '/Logic/%file_name%.%locale%.resx'
  -
    source: 'Site/*.resx'
    translation: '/Site/%locale%/%file_name%.%locale%.resx'
